name: List Directories and Their Latest Modification Time (Ubuntu)

on:
  schedule:
    - cron: '0 0 * * 0'  # Executa semanalmente, todo domingo à meia-noite
  workflow_dispatch:  # Permite execução manual

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: List Directories and Their Latest Modification Time in 'conteudo'
        run: |
          echo "Listing directories and their latest modification time (including files inside):"
          find ./conteudo -type d -exec stat --format '%n %y' {} \; | sed 's/\..*//'
