name: Delete Old Directories (Ubuntu)

on:
  schedule:
    - cron: '0 0 * * 0'  # Executa semanalmente, aos domingos à meia-noite
  workflow_dispatch:  # Permite execução manual

jobs:
  delete_old_directories:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
          fetch-depth: 0  # Garante o histórico completo para verificar datas de commit

      - name: Delete Directories If All Files Are Older Than 20 Days
        run: |
          set -e  # Interrompe o script em caso de erro
          echo "Checking directories where all files are older than 20 days..."

          if [ -d "./conteudo" ]; then
            find ./conteudo -mindepth 1 -maxdepth 1 -type d | while read dir; do
              dir_name=$(basename "$dir")
              all_old=true  # Assume que todos os arquivos são antigos

              # Verifica cada arquivo no diretório
              find "$dir" -type f | while read file; do
                last_commit_timestamp=$(git log -1 --pretty=format:"%ct" -- "$file")
                current_timestamp=$(date +%s)
                days_diff=$(( (current_timestamp - last_commit_timestamp) / 86400 ))

                # Se encontrar um arquivo ainda válido, cancela a exclusão
                if [ "$days_diff" -le 20 ]; then
                  all_old=false
                  break
                fi
              done

              # Remove a pasta somente se todos os arquivos forem antigos
              if [ "$all_old" = true ]; then
                echo "Deleting directory: $dir_name (all files older than 20 days)"
                rm -rf "$dir"
              else
                echo "Directory $dir_name has recent files, skipping deletion."
              fi
            done
          else
            echo "Directory './conteudo' does not exist."
          fi

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add -A
          git commit -m "Deleted directories with all files older than 20 days" || echo "No changes to commit"
          git push origin HEAD:${{ github.ref }}