name: Delete Old Folders and Files in 'conteudo' (Ubuntu)

on:
  schedule:
    - cron: '0 0 * * 0'  # Executa semanalmente, todo domingo à meia-noite
  workflow_dispatch:  # Permite execução manual

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Delete Files Older Than 20 Days in 'conteudo' Folder
        run: |
          echo "Deleting files older than 20 days..."
          find ./conteudo -type f -mtime +20 -exec rm -f {} \; || echo "No files found to delete"
          
      - name: Delete Directories Older Than 20 Days in 'conteudo' Folder
        run: |
          echo "Deleting directories older than 20 days..."
          find ./conteudo -type d -mtime +20 -exec rm -rf {} \; || echo "No directories found to delete"

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add .
          git commit -m "Deleted old folders and files automatically" || echo "No changes to commit"
          git push origin HEAD:${{ github.ref }}
