name: List Directories and Their Latest Git Commit Date (Ubuntu)

on:
  schedule:
    - cron: '0 0 * * 0'  # Executa semanalmente, todo domingo à meia-noite
  workflow_dispatch:  # Permite execução manual

jobs:
  list_directories:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: List Directories and Latest Commit Date
        run: |
          echo "Generating report of directories and their latest commit dates..."
          if [ -d "./conteudo" ]; then
            # Criar ou sobrescrever o ficheiro de relatório
            echo "Name, Last Commit Message, Last Commit Date" > directory_modifications.txt
            
            # Iterar por todas as pastas em './conteudo'
            for dir in $(find ./conteudo -mindepth 1 -maxdepth 1 -type d); do
              # Obter o nome da pasta
              dir_name=$(basename "$dir")

              # Obter a última mensagem de commit
              last_commit_message=$(git log -1 --format="%s" -- "$dir")
              
              # Usar o formato desejado para a data do último commit
              _GIT_COMMIT_DATE=$(git log -1 --format=%cd --date=format:%Y%m%dh%H%M%S -- "$dir")

              # Adicionar a informação no ficheiro de relatório
              echo "$dir_name, $last_commit_message, $_GIT_COMMIT_DATE" >> directory_modifications.txt
            done
            
            echo "Report generated: directory_modifications.txt"
          else
            echo "Directory './conteudo' does not exist."
          fi
          
      - name: Commit and Push Changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add directory_modifications.txt
          git commit -m "Updated directory modification times report" || echo "No changes to commit"
          git push origin HEAD:${{ github.ref }}
