name: List Directories and Their Latest Git Commit Date (Ubuntu)

on:
  schedule:
    - cron: '0 0 * * 0'  # Executa semanalmente, todo domingo à meia-noite
  workflow_dispatch:  # Permite execução manual

jobs:
  list_directories:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: List Directories and Latest Commit Date
        run: |
          echo "Generating report of directories and their latest commit dates..."
          if [ -d "./conteudo" ]; then
            # Criar ou sobrescrever o ficheiro de relatório
            echo "Name, Last Commit Message, Last Commit Date" > directory_modifications.txt

            # Listar todos os diretórios na pasta 'conteudo'
            for dir in $(find ./conteudo -mindepth 1 -maxdepth 1 -type d); do
              # Obter o nome do diretório
              dir_name=$(basename "$dir")

              # Obter o último commit para o diretório usando git log
              last_commit=$(git log -1 --pretty=format:"%C(yellow)%cd%Creset" --date=format:"%Y%m%d%H%M%S" -- "$dir")
              last_commit_message=$(git log -1 --pretty=format:"%s" -- "$dir")
              
              # Adicionar as informações no ficheiro de relatório
              echo "$dir_name, $last_commit_message, $last_commit" >> directory_modifications.txt
            done

            echo "Report generated: directory_modifications.txt"
          else
            echo "Directory './conteudo' does not exist."
          fi
          
      - name: Commit and Push Changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add directory_modifications.txt
          git commit -m "Updated directory modification times report" || echo "No changes to commit"
          git push origin HEAD:${{ github.ref }}
