name: List Directories and Their Latest Git Commit Date (Ubuntu)

on:
  schedule:
    - cron: '0 0 * * 0'  # Executa semanalmente, todo domingo à meia-noite
  workflow_dispatch:  # Permite execução manual

jobs:
  list_directories:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: List Directories and Latest Commit Date
        run: |
          echo "Generating report of directories and their latest commit dates..."
          if [ -d "./conteudo" ]; then
            > directory_modifications.txt
            for dir in $(find ./conteudo -mindepth 1 -maxdepth 1 -type d); do
              last_commit=$(git log -1 --format="%ci" -- "$dir")
              echo "$dir: $last_commit" >> directory_modifications.txt
            done
            echo "Report generated: directory_modifications.txt"
          else
            echo "Directory './conteudo' does not exist."
          
      - name: Commit and Push Changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add directory_modifications.txt
          git commit -m "Updated directory modification times report" || echo "No changes to commit"
          git push origin HEAD:${{ github.ref }}
