name: List Directories and Their Latest Modification Time (Ubuntu)

on:
  schedule:
    - cron: '0 0 * * 0'  # Executa semanalmente, todo domingo à meia-noite
  workflow_dispatch:  # Permite execução manual

jobs:
  list_directories:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: List Directories and Latest Modification Time in 'conteudo'
        run: |
          echo "Generating report of directories and their latest modification times..."
          if [ -d "./conteudo" ]; then
            # Gerar relatório das datas de modificação
            for dir in $(find ./conteudo -type d); do
              # Obter a data de modificação mais recente entre os ficheiros no diretório
              last_mod=$(find "$dir" -type f -printf "%T@ %p\n" 2>/dev/null | sort -n | tail -1)
              if [ -z "$last_mod" ]; then
                echo "$dir: No files"
              else
                timestamp=$(echo "$last_mod" | cut -d' ' -f1)
                date_mod=$(date -d @$timestamp +"%Y-%m-%d %H:%M:%S")
                echo "$dir: $date_mod"
              fi
            done > directory_modifications.txt
            echo "Report generated: directory_modifications.txt"
          else
            echo "Directory './conteudo' does not exist."
          fi

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add directory_modifications.txt
          git commit -m "Updated directory modification times report" || echo "No changes to commit"
          git push origin HEAD:${{ github.ref }}
