name: Delete Old Folders and Files in 'conteudo' (Ubuntu)

on:
  schedule:
    - cron: '0 0 * * 0'  # Runs weekly, every Sunday at midnight
  workflow_dispatch:  # Allows manual execution

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
          fetch-depth: 0  # Ensure full history is fetched

      - name: Delete Old Directories Based on Last Commit Date
        run: |
          echo "Checking for directories and files older than 20 days based on last commit date..." > cleanup_report.txt
          
          # Get the current date in seconds since epoch
          current_date=$(date +%s)
          
          # List all directories in the 'conteudo' folder
          for dir in $(find ./conteudo -mindepth 1 -maxdepth 1 -type d); do
            # Get the directory name
            dir_name=$(basename "$dir")

            # Get the last commit for the directory using git log
            last_commit_message=$(git log -1 --pretty=format:"%s" -- "$dir")
            last_commit_date=$(git log -1 --pretty=format:"%cd" --date=format:"%Y-%m-%d %H:%M:%S" -- "$dir")

            # Convert last commit date to timestamp
            last_commit_timestamp=$(date -d "$last_commit_date" +%s)

            # Calculate the difference in days
            diff_days=$(( (current_date - last_commit_timestamp) / (60*60*24) ))

            # Delete directories older than 20 days
            if [ $diff_days -ge 20 ]; then
              echo "Deleting directory: $dir_name (last commit date: $last_commit_date)" | tee -a cleanup_report.txt
              rm -rf "$dir"
            else
              echo "Directory not old enough: $dir_name (last commit date: $last_commit_date)" | tee -a cleanup_report.txt
            fi
          done

          echo "Old directories checked based on last commit date." | tee -a cleanup_report.txt

      - name: Delete Files Older Than 20 Days in 'conteudo' Folder
        run: |
          echo "Deleting files older than 20 days..." | tee -a cleanup_report.txt
          find ./conteudo -type f -mtime +20 -exec rm -f {} \; -exec echo "Deleted file: {}" \; || echo "No files found to delete" | tee -a cleanup_report.txt
          echo "Old files deleted." | tee -a cleanup_report.txt

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add cleanup_report.txt
          git commit -m "Cleanup report: Deleted old folders and files automatically based on last commit date" || echo "No changes to commit"
          git push origin HEAD:${{ github.ref }}
